# Default settings -- CH: 5, bitrate: 110 kbit/s, prf: 64 MHz, plen: 1024 symbols, gain: 11.5 dB
channel: 2                        # 1, 2, 3, 4, 5, 7
bitrate: 110_kbps                 # 110_kbps, 6810_kbps, 850_kbps
pulse_repetition_frequecy: 16_MHz # 16_MHz, 64_MHz
preamble_length: 2048             # 64, 128, 256, 512, 1024, 2048
gain: 33.0                        # from 0 to 33.5 every 0.5 db